# Generated by Django 5.2.1 on 2025-09-11 11:22

import ckeditor_uploader.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='seo_optimization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagename', models.CharField(default=None, max_length=255, null=True, verbose_name='Page Name')),
                ('pageslug', models.CharField(default=None, max_length=160, null=True, verbose_name='Page Url')),
                ('metatitle', models.CharField(default=None, max_length=75, null=True, verbose_name='Page Meta Title')),
                ('metadescription', models.TextField(default=None, max_length=175, null=True, verbose_name='Page Meta Des')),
                ('pagecontent', ckeditor_uploader.fields.RichTextUploadingField(default='No News', null=True, verbose_name='Long Discretion')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=5, null=True, verbose_name='Order')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
