# Generated by Django 5.2.1 on 2025-09-11 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('age', models.CharField(blank=True, choices=[('young-children', 'Young Children (5–12y)'), ('teenagers', 'Teenagers (13–19y)'), ('young-adults', 'Young Adults (20–35y)'), ('adults', 'Adults (36–60y)'), ('senior-citizens', 'Senior Citizens (60+)')], max_length=20, null=True)),
                ('Cross_Sector', models.CharField(blank=True, choices=[('science-technology', 'Science and Technology'), ('entrepreneurship', 'Entrepreneurship'), ('environment', 'Environment and Sustainability'), ('social-media', 'Social Media and Content Creation'), ('health-wellness', 'Health and Wellness'), ('civic-engagement', 'Civic Engagement'), ('diversity-inclusion', 'Diversity and Inclusion'), ('spirituality', 'Spirituality and Philosophy')], max_length=20, null=True)),
                ('phone', models.CharField(max_length=255, null=True, verbose_name='phone')),
                ('email', models.CharField(max_length=255, null=True, verbose_name='email')),
                ('country', models.CharField(max_length=255, null=True, verbose_name='country')),
                ('city', models.CharField(max_length=255, null=True, verbose_name='city')),
                ('description', models.TextField(blank=True, null=True)),
                ('sent_date', models.DateTimeField(auto_now_add=True)),
                ('proof', models.FileField(upload_to='proofs/')),
                ('agree_terms', models.BooleanField(default=False)),
                ('agree_payment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BrandPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('email', models.CharField(max_length=255, null=True, verbose_name='Email')),
                ('Logo', models.FileField(default=None, max_length=255, null=True, upload_to='bplogo/')),
                ('url', models.CharField(max_length=255, verbose_name='URL')),
                ('post_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
        migrations.CreateModel(
            name='SubscribeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='Name')),
                ('email', models.CharField(max_length=255, null=True, verbose_name='email')),
                ('ip', models.CharField(max_length=255, verbose_name='User Ip')),
                ('country', models.CharField(max_length=255, verbose_name='Country')),
                ('city', models.CharField(max_length=255, verbose_name='City')),
                ('subscribe_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
        ),
        migrations.CreateModel(
            name='vouenquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150)),
                ('interestedin', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(upload_to='vouprofilepic/')),
                ('biography', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('done', 'Done'), ('pending', 'Pending')], default='Article Live', max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CareerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100, null=True, verbose_name='Name')),
                ('mobnumber', models.CharField(default=None, max_length=100, null=True, verbose_name='Contact Number')),
                ('email', models.CharField(default=None, max_length=160, null=True, verbose_name='email')),
                ('location', models.CharField(default=None, max_length=160, null=True, verbose_name='location')),
                ('nationality', models.CharField(default=None, max_length=160, null=True, verbose_name='nationality')),
                ('language', models.CharField(default=None, max_length=160, null=True, verbose_name='language')),
                ('address', models.TextField(default='na', null=True, verbose_name='address')),
                ('highestedu', models.CharField(default=None, max_length=100, null=True, verbose_name='Higher Education')),
                ('fos', models.CharField(default=None, max_length=100, null=True, verbose_name='FieldOfStudy')),
                ('occupation', models.CharField(default=None, max_length=160, null=True, verbose_name='occupation')),
                ('journalexp', models.CharField(default=None, max_length=160, null=True, verbose_name='journalexp')),
                ('lastwork', models.CharField(default=None, max_length=160, null=True, verbose_name='lastwork')),
                ('portfolio', models.CharField(default=None, max_length=160, null=True, verbose_name='Portfolio')),
                ('equipment', models.CharField(default=None, max_length=160, null=True, verbose_name='Equipment')),
                ('softwareskill', models.CharField(default=None, max_length=160, null=True, verbose_name='Softwareskill')),
                ('availability', models.CharField(default=None, max_length=160, null=True, verbose_name='Availability')),
                ('resume', models.FileField(default=None, max_length=255, null=True, upload_to='cv/')),
                ('whyjoin', models.TextField(default='na', null=True, verbose_name='Why Join')),
                ('anysegment', models.TextField(default='na', null=True, verbose_name='Anysegment')),
                ('status', models.CharField(choices=[('selected', 'Selected'), ('NotSelected', 'Not Selected')], default='NotSelected', max_length=20, null=True)),
                ('remark', models.TextField(default='na', null=True, verbose_name='Remark')),
                ('post_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False, verbose_name='Active')),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='post_management.sub_category', verbose_name='Select Category')),
            ],
        ),
        migrations.CreateModel(
            name='jobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(default=None, max_length=65, null=True, verbose_name='Name')),
                ('education', models.CharField(default=None, max_length=100, null=True, verbose_name='Higher Education')),
                ('experience', models.CharField(default=None, max_length=160, null=True, verbose_name='Work Experience')),
                ('expsalary', models.CharField(default=None, max_length=160, null=True, verbose_name='Expected Salary')),
                ('covernote', models.TextField(default='na', null=True, verbose_name='Cover Note')),
                ('resume', models.FileField(default=None, max_length=255, null=True, upload_to='cv/')),
                ('status', models.CharField(choices=[('selected', 'Selected'), ('NotSelected', 'Not Selected')], default='NotSelected', max_length=20)),
                ('remark', models.TextField(default='na', null=True, verbose_name='Remark')),
                ('post_date', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='post_management.category', verbose_name='Select Category')),
            ],
        ),
        migrations.CreateModel(
            name='RegForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(max_length=255, null=True, verbose_name='Person Name')),
                ('company_name', models.CharField(max_length=255, null=True, verbose_name='Company Name')),
                ('company_address', models.CharField(max_length=255, null=True, verbose_name='Company Address')),
                ('phone', models.CharField(max_length=255, null=True, verbose_name='phone')),
                ('email', models.CharField(max_length=255, null=True, verbose_name='email')),
                ('city', models.CharField(max_length=255, null=True, verbose_name='city')),
                ('country', models.CharField(max_length=255, null=True, verbose_name='country')),
                ('diesgantion', models.CharField(max_length=255, null=True, verbose_name='Designation')),
                ('enquiry_type', models.CharField(max_length=255, null=True, verbose_name='enquiry_type')),
                ('executive_names', models.CharField(max_length=255, null=True, verbose_name='executive names')),
                ('walk_in', models.CharField(max_length=255, null=True, verbose_name='walk_in')),
                ('ip', models.CharField(max_length=255, verbose_name='User Ip')),
                ('reg_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('source_from', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='post_management.sub_category', verbose_name='Select Category')),
            ],
        ),
    ]
