# Generated by Django 5.2.1 on 2025-09-11 11:22

import autoslug.fields
import ckeditor_uploader.fields
import django.db.models.deletion
import image_cropping.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pagename', models.CharField(default=None, max_length=150, null=True, verbose_name='Page Name')),
                ('Content', ckeditor_uploader.fields.RichTextUploadingField(default='No News', null=True, verbose_name='Long Discretion')),
                ('pageimage', image_cropping.fields.ImageCropField(blank=True, max_length=255, null=True, upload_to='cms/', verbose_name='Page Image (1280X220px)')),
                ('slug', autoslug.fields.AutoSlugField(default=None, editable=False, max_length=200, null=True, populate_from='pagename', unique=True)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('viewcounter', models.IntegerField(default=0, null=True, verbose_name='Views')),
                ('post_status', models.IntegerField(default=100, null=True, verbose_name='Counter')),
                ('order', models.IntegerField(default=5, null=True, verbose_name='Order')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='setting_cms_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Content Management System',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='profile_setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_light', models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Logo Light (500X100px)')),
                ('logo_dark', models.ImageField(blank=True, null=True, upload_to='logo/', verbose_name='Logo Dark (500X100px)')),
                ('footer_img', models.ImageField(blank=True, null=True, upload_to='profile_image/', verbose_name='Footer Image (1920X365px)')),
                ('body_img', models.ImageField(blank=True, null=True, upload_to='profile_image/', verbose_name='Body Image (1920X365px)')),
                ('background_theme_light', models.CharField(blank=True, default='#FFFFFF', help_text='Light Background', max_length=7, null=True, verbose_name='background Theme Light')),
                ('background_theme_dark', models.CharField(blank=True, default='#000000', help_text='Dark Background', max_length=7, null=True, verbose_name='background Theme Dark')),
                ('container_background', models.CharField(blank=True, default='#fcf8e7', help_text='container background in body', max_length=7, null=True, verbose_name='container background')),
                ('items_background', models.CharField(blank=True, default='#FFFFFF', help_text='items background in body', max_length=7, null=True, verbose_name='Items background')),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('phone_number1', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number 1')),
                ('phone_number2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone Number 2')),
                ('facbook', models.URLField(blank=True, null=True, verbose_name='Facebook')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='Twitter')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='Linkedin')),
                ('youtube', models.URLField(blank=True, null=True, verbose_name='Youtube')),
                ('main_office_address', models.TextField(blank=True, max_length=200, null=True, verbose_name='Main Office Address')),
                ('branch_office_address', models.TextField(blank=True, max_length=255, null=True, verbose_name='Branch Office Address')),
                ('google_map', models.TextField(blank=True, help_text='Embed Code', null=True, verbose_name='Google Map')),
                ('copyright', models.CharField(blank=True, max_length=255, null=True, verbose_name='Copyright')),
                ('establish_at', models.DateField(blank=True, null=True, verbose_name='Establish At')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='setting_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile Setting',
            },
        ),
    ]
