# Generated by Django 5.2.6 on 2026-01-09 05:26

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('name_hindi', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'District',
                'verbose_name_plural': 'Districts',
                'db_table': 'nanhe_patrakar_districts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_hindi', models.CharField(blank=True, max_length=100, null=True)),
                ('age_groups', models.CharField(help_text='Comma-separated: A,B,C', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'db_table': 'nanhe_patrakar_topics',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ChildProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(16)])),
                ('age_group', models.CharField(choices=[('A', 'Group A (8-10 years)'), ('B', 'Group B (11-13 years)'), ('C', 'Group C (14-16 years)')], max_length=1)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('school_name', models.CharField(blank=True, max_length=255, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='child_photos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nanhe_patrakar.district')),
            ],
            options={
                'verbose_name': 'Child Profile',
                'verbose_name_plural': 'Child Profiles',
                'db_table': 'nanhe_patrakar_child_profiles',
            },
        ),
        migrations.CreateModel(
            name='ParentConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_guidance_agreed', models.BooleanField(default=False)),
                ('publication_consent', models.BooleanField(default=False)),
                ('data_usage_agreed', models.BooleanField(default=False)),
                ('consent_text', models.TextField()),
                ('consent_given_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='consent', to='nanhe_patrakar.childprofile')),
            ],
            options={
                'verbose_name': 'Parent Consent',
                'verbose_name_plural': 'Parent Consents',
                'db_table': 'nanhe_patrakar_parent_consents',
            },
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('REGISTERED_NOT_ACTIVATED', 'Registered Not Activated'), ('PAID_AWAITING_APP', 'Paid Awaiting App'), ('VERIFIED_PENDING_SUBMISSION', 'Verified Pending Submission'), ('ACTIVE', 'Active')], default='REGISTERED_NOT_ACTIVATED', max_length=50)),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='parent_docs/')),
                ('id_proof_verified', models.BooleanField(default=False)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('terms_accepted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nanhe_patrakar.district')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Parent Profile',
                'verbose_name_plural': 'Parent Profiles',
                'db_table': 'nanhe_patrakar_parent_profiles',
            },
        ),
        migrations.AddField(
            model_name='childprofile',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='nanhe_patrakar.parentprofile'),
        ),
        migrations.CreateModel(
            name='ParticipationOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, default=599.0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=20)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_signature', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('invoice_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='nanhe_patrakar.parentprofile')),
            ],
            options={
                'verbose_name': 'Participation Order',
                'verbose_name_plural': 'Participation Orders',
                'db_table': 'nanhe_patrakar_participation_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('ARTICLE', 'Article'), ('POEM', 'Poem'), ('EXPERIENCE', 'Experience'), ('SPEECH', 'Speech')], max_length=20)),
                ('language', models.CharField(choices=[('HINDI', 'Hindi'), ('ENGLISH', 'English'), ('LOCAL', 'Local Language')], max_length=20)),
                ('content_text', models.TextField(blank=True, null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='submissions/audio/')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='submissions/video/')),
                ('media_description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('UNDER_REVIEW', 'Under Review'), ('REVISION_REQUESTED', 'Revision Requested'), ('RESUBMITTED', 'Resubmitted'), ('APPROVED', 'Approved'), ('PUBLISHED', 'Published'), ('REJECTED', 'Rejected'), ('CERTIFICATE_ISSUED', 'Certificate Issued')], default='DRAFT', max_length=30)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('revision_reason', models.TextField(blank=True, null=True)),
                ('editorial_notes', models.TextField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('published_url', models.URLField(blank=True, null=True)),
                ('seo_tags', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='nanhe_patrakar.childprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_submissions', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='nanhe_patrakar.topic')),
            ],
            options={
                'verbose_name': 'Submission',
                'verbose_name_plural': 'Submissions',
                'db_table': 'nanhe_patrakar_submissions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('child_name', models.CharField(max_length=200)),
                ('age_group', models.CharField(max_length=1)),
                ('certificate_pdf', models.FileField(upload_to='certificates/')),
                ('verification_code', models.CharField(max_length=50, unique=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('emailed_to_parent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='nanhe_patrakar.submission')),
            ],
            options={
                'verbose_name': 'Certificate',
                'verbose_name_plural': 'Certificates',
                'db_table': 'nanhe_patrakar_certificates',
            },
        ),
    ]
