# Generated by Django 5.2.6 on 2026-01-09 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanhe_patrakar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Program name in English', max_length=200)),
                ('name_hindi', models.CharField(help_text='Program name in Hindi', max_length=200)),
                ('slug', models.SlugField(help_text='URL friendly name', unique=True)),
                ('description', models.TextField(help_text='Program description in English')),
                ('description_hindi', models.TextField(help_text='Program description in Hindi')),
                ('price', models.DecimalField(decimal_places=2, help_text='Participation fee in INR', max_digits=10)),
                ('min_age', models.IntegerField(default=8, help_text='Minimum age for participation')),
                ('max_age', models.IntegerField(default=16, help_text='Maximum age for participation')),
                ('android_app_url', models.URLField(blank=True, help_text='Google Play Store URL', null=True)),
                ('ios_app_url', models.URLField(blank=True, help_text='Apple App Store URL', null=True)),
                ('age_group_a_min', models.IntegerField(default=8)),
                ('age_group_a_max', models.IntegerField(default=10)),
                ('age_group_b_min', models.IntegerField(default=11)),
                ('age_group_b_max', models.IntegerField(default=13)),
                ('age_group_c_min', models.IntegerField(default=14)),
                ('age_group_c_max', models.IntegerField(default=16)),
                ('is_active', models.BooleanField(default=True)),
                ('registration_open', models.BooleanField(default=True, help_text='Accept new registrations')),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('privacy_policy', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=0)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='program_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Program',
                'verbose_name_plural': 'Programs',
                'db_table': 'nanhe_patrakar_programs',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'Registered'), ('PAYMENT_PENDING', 'Payment Pending'), ('PAYMENT_COMPLETED', 'Payment Completed'), ('ACTIVE', 'Active')], default='REGISTERED', max_length=50),
        ),
        migrations.AlterField(
            model_name='participationorder',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='program',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='nanhe_patrakar.program'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participationorder',
            name='program',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='nanhe_patrakar.program'),
            preserve_default=False,
        ),
    ]
