# Generated by Django 5.2.6 on 2026-01-09 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanhe_patrakar', '0002_program_alter_parentprofile_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmissionMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('IMAGE', 'Image'), ('VIDEO', 'Video'), ('AUDIO', 'Audio')], max_length=10)),
                ('file', models.FileField(upload_to='submissions/media/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_files', to='nanhe_patrakar.submission')),
            ],
            options={
                'verbose_name': 'Submission Media',
                'verbose_name_plural': 'Submission Media',
                'db_table': 'nanhe_patrakar_submission_media',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
