# Generated by Django 5.2.6 on 2026-01-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanhe_patrakar', '0003_submissionmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='childprofile',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='child_docs/'),
        ),
    ]
