# Generated by Django 5.2.6 on 2026-01-17 12:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanhe_patrakar', '0004_childprofile_id_proof'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childprofile',
            name='age',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(16)]),
        ),
        migrations.AlterField(
            model_name='childprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
