# Generated by Django 5.2.6 on 2026-01-22 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nanhe_patrakar', '0005_alter_childprofile_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childprofile',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nanhe_patrakar.district'),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='parentprofile',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='nanhe_patrakar.district'),
        ),
    ]
