# Generated by Django 5.2.1 on 2025-09-30 10:35

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_management', '0002_newsfrom_newspost_newsfrom_videonews_newsfrom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='newsfrom',
            new_name='newstype',
        ),
    ]
