# Generated by Django 5.2.6 on 2026-01-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_management', '0004_appuser_alter_newspost_post_image_alter_tag_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Notification Title')),
                ('message', models.TextField(verbose_name='Notification Body')),
                ('image', models.ImageField(blank=True, null=True, upload_to='notifications/', verbose_name='Big Image (Optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=False, verbose_name='Sent to Users?')),
            ],
            options={
                'verbose_name': 'Custom Notification',
                'verbose_name_plural': 'Custom Notifications',
            },
        ),
    ]
