# Generated by Django 5.2.1 on 2025-09-11 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities_light', '0011_alter_city_country_alter_city_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('dial_code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Journalist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, unique=True)),
                ('parent_organisations', models.CharField(blank=True, max_length=155, null=True)),
                ('registration_type', models.CharField(blank=True, choices=[('artist', 'Artist'), ('journalist', 'Journalist'), ('organisation', 'Organisation')], max_length=50, null=True)),
                ('organisation_name', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('alternative_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=10, null=True)),
                ('social_media_links', models.JSONField(blank=True, default=dict, null=True)),
                ('passport_document', models.FileField(blank=True, null=True, upload_to='documents/passport')),
                ('government_document', models.FileField(blank=True, null=True, upload_to='documents/government/')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pictures/')),
                ('banner', models.ImageField(blank=True, null=True, upload_to='banner/')),
                ('biography', models.TextField(blank=True, null=True, verbose_name='biography (max 120 characters)')),
                ('terms_accepted', models.BooleanField(default=False)),
                ('gallery_post_limit', models.PositiveIntegerField(default=8, verbose_name='Gallery Post Limit')),
                ('password', models.CharField(default='defaultpassword', max_length=128)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('approved', 'Approved')], default='inactive', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.city')),
                ('nationality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.country')),
                ('selected_equipment', models.ManyToManyField(blank=True, to='journalist.equipment')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities_light.region')),
                ('languages', models.ManyToManyField(blank=True, to='journalist.language')),
                ('higher_education', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journalist.qualification')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='journalist')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('caption', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='inactive', max_length=8)),
                ('post_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('journalist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='journalist.journalist')),
            ],
        ),
    ]
