# Generated by Django 5.2.6 on 2025-12-24 11:09

import django.db.models.deletion
from django.db import migrations, models


def clear_author_data(apps, schema_editor):
    """Clear author data before changing foreign key"""
    getnewsdata = apps.get_model('journalist', 'getnewsdata')
    getnewsdata.objects.all().update(author_id=None)


def reverse_clear_author_data(apps, schema_editor):
    """Reverse operation - nothing to do"""
    pass


def drop_old_constraint_and_create_new(apps, schema_editor):
    """Drop old foreign key constraint and create new one pointing to Journalist"""
    with schema_editor.connection.cursor() as cursor:
        # Find and drop the old foreign key constraint (try common constraint names)
        try:
            cursor.execute("""
                SELECT CONSTRAINT_NAME 
                FROM information_schema.KEY_COLUMN_USAGE 
                WHERE TABLE_SCHEMA = DATABASE() 
                AND TABLE_NAME = 'journalist_getnewsdata' 
                AND COLUMN_NAME = 'author_id' 
                AND REFERENCED_TABLE_NAME = 'auth_user'
            """)
            result = cursor.fetchone()
            if result:
                constraint_name = result[0]
                cursor.execute(f"""
                    ALTER TABLE journalist_getnewsdata 
                    DROP FOREIGN KEY {constraint_name}
                """)
        except Exception as e:
            # Try to drop with the known constraint name from error
            try:
                cursor.execute("""
                    ALTER TABLE journalist_getnewsdata 
                    DROP FOREIGN KEY journalist_getnewsdata_author_id_a7d82c2c_fk_auth_user_id
                """)
            except:
                pass
        
        # Create new foreign key constraint pointing to journalist_journalist
        cursor.execute("""
            ALTER TABLE journalist_getnewsdata 
            ADD CONSTRAINT journalist_getnewsdata_author_id_fk_journalist_journalist_id 
            FOREIGN KEY (author_id) REFERENCES journalist_journalist(id) 
            ON DELETE CASCADE
        """)


def reverse_drop_constraint(apps, schema_editor):
    """Reverse: drop new constraint and recreate old one"""
    with schema_editor.connection.cursor() as cursor:
        # Drop new constraint
        cursor.execute("""
            ALTER TABLE journalist_getnewsdata 
            DROP FOREIGN KEY journalist_getnewsdata_author_id_fk_journalist_journalist_id
        """)
        # Recreate old constraint (if needed for rollback)
        cursor.execute("""
            ALTER TABLE journalist_getnewsdata 
            ADD CONSTRAINT journalist_getnewsdata_author_id_a7d82c2c_fk_auth_user_id 
            FOREIGN KEY (author_id) REFERENCES auth_user(id) 
            ON DELETE CASCADE
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('journalist', '0002_getnewsdata_newsimage_newsvideo'),
    ]

    operations = [
        # First, clear any existing author data to avoid constraint issues
        migrations.RunPython(clear_author_data, reverse_clear_author_data),
        # Drop old constraint and create new one using raw SQL
        migrations.RunPython(drop_old_constraint_and_create_new, reverse_drop_constraint),
        # Then alter the field in Django's state
        migrations.AlterField(
            model_name='getnewsdata',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_posts', to='journalist.journalist'),
        ),
    ]
