# Generated by Django 5.2.6 on 2025-12-24 16:40

from django.db import migrations


def fix_foreign_key_constraint(apps, schema_editor):
    """Fix foreign key constraint to point to Journalist instead of User"""
    with schema_editor.connection.cursor() as cursor:
        # Find the old constraint name
        cursor.execute("""
            SELECT CONSTRAINT_NAME 
            FROM information_schema.KEY_COLUMN_USAGE 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'journalist_getnewsdata' 
            AND COLUMN_NAME = 'author_id' 
            AND REFERENCED_TABLE_NAME = 'auth_user'
        """)
        result = cursor.fetchone()
        
        if result:
            constraint_name = result[0]
            # Drop the old foreign key constraint
            cursor.execute(f"""
                ALTER TABLE journalist_getnewsdata 
                DROP FOREIGN KEY {constraint_name}
            """)
        
        # Check if new constraint already exists
        cursor.execute("""
            SELECT CONSTRAINT_NAME 
            FROM information_schema.KEY_COLUMN_USAGE 
            WHERE TABLE_SCHEMA = DATABASE() 
            AND TABLE_NAME = 'journalist_getnewsdata' 
            AND COLUMN_NAME = 'author_id' 
            AND REFERENCED_TABLE_NAME = 'journalist_journalist'
        """)
        new_constraint = cursor.fetchone()
        
        if not new_constraint:
            # Create new foreign key constraint pointing to journalist_journalist
            cursor.execute("""
                ALTER TABLE journalist_getnewsdata 
                ADD CONSTRAINT journalist_getnewsdata_author_id_fk_journalist_journalist_id 
                FOREIGN KEY (author_id) REFERENCES journalist_journalist(id) 
                ON DELETE CASCADE
            """)


def reverse_fix_constraint(apps, schema_editor):
    """Reverse: recreate old constraint"""
    with schema_editor.connection.cursor() as cursor:
        # Drop new constraint
        cursor.execute("""
            ALTER TABLE journalist_getnewsdata 
            DROP FOREIGN KEY journalist_getnewsdata_author_id_fk_journalist_journalist_id
        """)
        # Recreate old constraint
        cursor.execute("""
            ALTER TABLE journalist_getnewsdata 
            ADD CONSTRAINT journalist_getnewsdata_author_id_a7d82c2c_fk_auth_user_id 
            FOREIGN KEY (author_id) REFERENCES auth_user(id) 
            ON DELETE CASCADE
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('journalist', '0003_alter_getnewsdata_author'),
    ]

    operations = [
        migrations.RunPython(fix_foreign_key_constraint, reverse_fix_constraint),
    ]
