# Generated by Django 5.2.6 on 2025-12-24 17:15

from django.db import migrations


def fix_news_description_charset(apps, schema_editor):
    """Convert news_description column to utf8mb4 charset"""
    with schema_editor.connection.cursor() as cursor:
        # Convert the column to utf8mb4
        cursor.execute("""
            ALTER TABLE journalist_getnewsdata 
            MODIFY COLUMN news_description TEXT 
            CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci
        """)


def reverse_fix_charset(apps, schema_editor):
    """Reverse: convert back to utf8 (if needed)"""
    with schema_editor.connection.cursor() as cursor:
        cursor.execute("""
            ALTER TABLE journalist_getnewsdata 
            MODIFY COLUMN news_description TEXT 
            CHARACTER SET utf8 COLLATE utf8_unicode_ci
        """)


class Migration(migrations.Migration):

    dependencies = [
        ('journalist', '0004_fix_getnewsdata_author_constraint'),
    ]

    operations = [
        migrations.RunPython(fix_news_description_charset, reverse_fix_charset),
    ]
