# Generated by Django 5.2.1 on 2025-09-11 11:22

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ad_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads_cat_name', models.CharField(default=None, max_length=255, null=True, unique=True, verbose_name='Ad Type')),
                ('ads_cat_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='ads_cat_name', unique=True)),
                ('ads_cat_status', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_url', models.CharField(default=None, max_length=255, null=True, verbose_name='Link URL')),
                ('ad_type', models.CharField(choices=[('stil', 'Image'), ('video', 'Video')], default='active', max_length=8, verbose_name='Ad Type')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('ad_image', models.FileField(upload_to='ads/')),
                ('ad_counter', models.IntegerField(default=None, null=True, verbose_name='Counter')),
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('post_date', models.DateTimeField(auto_now=True)),
                ('post_status', models.IntegerField(default=0, null=True)),
                ('ads_cat', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='ad_management.ad_category', verbose_name='Select Ad Type')),
            ],
        ),
    ]
